name = "shortradar-stats-updater"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Free tier cron limits: 100k requests/day. 1 trigger every 5 mins = 288/day.
[triggers]
crons = ["*/5 * * * *"]

[vars]
# Add database credentials securely in Cloudflare dash or via secrets CLI